export const _students = [
	{
		tId: 1,
		id: 1,
		sMobile: '86071946789',
		sName: 'Sojwal Gosavi',
		sEmail: 'sojwal@gmail.com',
		sAddress: 'Kanadi Mala, Sinnar, Nashik',
	},
	{
		tId: 1,
		id: 2,
		sMobile: '9876543210',
		sName: 'John Doe',
		sEmail: 'john.doe@example.com',
		sAddress: '123 Main Street, Anytown, USA',
	},
	{
		tId: 1,
		id: 3,
		sMobile: '1234567890',
		sName: 'Alice Smith',
		sEmail: 'alice.smith@example.com',
		sAddress: '456 Elm Street, Springfield, USA',
	},
	{
		tId: 1,
		id: 4,
		sMobile: '5556667777',
		sName: 'Bob Johnson',
		sEmail: 'bob.johnson@example.com',
		sAddress: '789 Oak Avenue, Smalltown, USA',
	},
	{
		tId: 1,
		id: 5,
		sMobile: '9876543210',
		sName: 'Mary Brown',
		sEmail: 'mary.brown@example.com',
		sAddress: '1011 Pine Road, Villageville, USA',
	},
	{
		tId: 1,
		id: 6,
		sMobile: '3334445555',
		sName: 'Emily Davis',
		sEmail: 'emily.davis@example.com',
		sAddress: '1314 Maple Court, Townsville, USA',
	},
	{
		tId: 1,
		id: 7,
		sMobile: '7778889999',
		sName: 'Michael Wilson',
		sEmail: 'michael.wilson@example.com',
		sAddress: '1516 Birch Lane, Hamletville, USA',
	},
	{
		tId: 1,
		id: 8,
		sMobile: '1112223333',
		sName: 'Sophia Taylor',
		sEmail: 'sophia.taylor@example.com',
		sAddress: '1718 Cedar Street, Villagetown, USA',
	},
	{
		tId: 1,
		id: 9,
		sMobile: '4445556666',
		sName: 'James Anderson',
		sEmail: 'james.anderson@example.com',
		sAddress: '1920 Pine Avenue, Cityville, USA',
	},
	{
		tId: 1,
		id: 10,
		sMobile: '8889990000',
		sName: 'Emma Martinez',
		sEmail: 'emma.martinez@example.com',
		sAddress: '2122 Elm Drive, Metropolis, USA',
	},
	{
		tId: 1,
		id: 11,
		sMobile: '2223334444',
		sName: 'Daniel Hernandez',
		sEmail: 'daniel.hernandez@example.com',
		sAddress: '2324 Oak Road, Megacity, USA',
	},
	{
		tId: 1,
		id: 12,
		sMobile: '6667778888',
		sName: 'Olivia Nelson',
		sEmail: 'olivia.nelson@example.com',
		sAddress: '2526 Maple Street, Gigatown, USA',
	},
	{
		tId: 1,
		id: 13,
		sMobile: '9990001111',
		sName: 'Alexander White',
		sEmail: 'alexander.white@example.com',
		sAddress: '2728 Cedar Avenue, Ultracity, USA',
	},
	{
		tId: 1,
		id: 14,
		sMobile: '5556667777',
		sName: 'Ava Carter',
		sEmail: 'ava.carter@example.com',
		sAddress: '2930 Pine Lane, Cosmopolis, USA',
	},
	{
		tId: 1,
		id: 15,
		sMobile: '1112223333',
		sName: 'William Lee',
		sEmail: 'william.lee@example.com',
		sAddress: '3132 Elm Boulevard, Megatown, USA',
	},
	{
		tId: 1,
		id: 16,
		sMobile: '7778889999',
		sName: 'Mia Perez',
		sEmail: 'mia.perez@example.com',
		sAddress: '3334 Oak Street, Supercity, USA',
	},
	{
		tId: 1,
		id: 17,
		sMobile: '3334445555',
		sName: 'Benjamin Martin',
		sEmail: 'benjamin.martin@example.com',
		sAddress: '3536 Maple Court, Hypercity, USA',
	},
	{
		tId: 1,
		id: 18,
		sMobile: '8889990000',
		sName: 'Charlotte Thompson',
		sEmail: 'charlotte.thompson@example.com',
		sAddress: '3738 Cedar Drive, Ultratown, USA',
	},
	{
		tId: 1,
		id: 19,
		sMobile: '2223334444',
		sName: 'Ethan Garcia',
		sEmail: 'ethan.garcia@example.com',
		sAddress: '3940 Pine Road, Megalopolis, USA',
	},
	{
		tId: 1,
		id: 20,
		sMobile: '6667778888',
		sName: 'Amelia Martinez',
		sEmail: 'amelia.martinez@example.com',
		sAddress: '4142 Elm Lane, Gigatown, USA',
	},
]
